spring.application.name=clinica-multi-backend
server.port=8080

# ===============================
# BANCO DE DADOS POSTGRESQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5433/clinicaMultiTerapias
spring.datasource.username=clinicaMultiTerapias
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Configurações de Internacionalização e Timezone
spring.jackson.time-zone=America/Sao_Paulo
spring.jackson.locale=pt_BR
